version: 1.1.0-b{build}
clone_folder: c:\projects\poc
init:
  # Checking that DEP is enabled
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: git --version
  - ps: dir c:\
  - ps: $env:Path = $env:Path.Replace("Python27", "Python35-x64")

install:
  - ps: Write-Host "Installing requirements..."
  - ps: python --version
  - ps: python -m pip install pip --upgrade
  - ps: python -m pip install -r .\requirements.txt
  - ps: python -m pip list
  - ps: Write-Host "Configuring PoC..."
  - ps: cp .\tools\AppVeyor\config.private.ini .\py\
  - ps: cp .\tools\AppVeyor\my_project.vhdl .\tb\common\
  - ps: .\poc.ps1

build: off
