sudo: required
dist: trusty
language: python
python:
- "3.5"
addons:
  apt:
    packages:
# this will install gnat-4.6 (trusty)
    - gnat-4.8
    - grc
before_install:
- sudo apt-get install -y libgnat-4.8 grc
- sudo ./tools/Travis-CI/grc.setup.sh
install:
- pip3 install -r tools/Travis-CI/requirements.txt
before_script:
- ./tools/Travis-CI/ghdl.setup.sh
- ./tools/Travis-CI/poc.setup.sh
script:
- ./tools/Travis-CI/poc.run.sh
#after_success:
#- 
#after_failure:
#- 
#before_deploy:
#- 
#deploy:
#- 
#after_deploy:
#- 
#after_script:
#- 

