sudo: required
language: c
matrix:
  include:
#    - services: docker
#      script:
#        - cd dockerbuilds/trusty/ && docker build .
#    - services: docker
#      script:
#        - cd dockerbuilds/latest/ && docker build .
    - os: linux
      sudo: required
      install: true
      services: docker
      env: BLD=docker
      script:
        - wget https://raw.githubusercontent.com/1138-4EB/ghdl/add-docker-proof-to-travis/dist/docker-mcode-ubu_lat.sh
        - $DONTGRAB_SRCS=0
        - chmod +x ./docker-mcode-ubu_lat.sh && ./docker-mcode-ubu_lat.sh
        - ls
        - GHDL_TARBALL=$(ls ghdl*.tgz)
        - docker run --name ghdl_cmp -itv $(pwd):/wrk:Z python:3.5.3-slim sh -c "GHDL_TARBALL=$(ls ghdl*.tgz) && cd /wrk && sh ./tools/Travis-CI/build.sh $BLD"

#  - dimg=ghdl/ghdl-tools:img-pythonslim_cmp-poc
#  - do=docompile.sh
#  - docker pull $dimg
#  - chmod u+w+x $do
#  - docker run --name froga -itv $(pwd):/scripts:Z $dimg bash -c "cd /scripts && sh $do && exit"