language: python
python: "3.5"
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install -y libgnat-4.8
        - sudo ./tools/Travis-CI/grc.setup.sh
      install:
        - pip3 install -r tools/Travis-CI/requirements.txt
      before_script:
        - ./tools/Travis-CI/ghdl.setup.sh
        - ./tools/Travis-CI/poc.setup.sh
      script:
        - ./tools/Travis-CI/poc.run.sh
# experimental without sudo rights
    - os: linux
      addons:
        apt:
          packages:
            - gnat-5
      install:
        - pip3 install -r tools/Travis-CI/requirements.txt
      before_script:
        - ./tools/Travis-CI/ghdl.setup.sh
        - ./tools/Travis-CI/poc.setup.sh
      script:
        - ./tools/Travis-CI/poc.run.sh
